// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGSYQrq8_MBglWPbiAhp2BgNnx5FBIzYk',
    appId: '1:229653211107:web:d349899f5f521e313be2d6',
    messagingSenderId: '229653211107',
    projectId: 'fir-crud-a1a2e',
    authDomain: 'fir-crud-a1a2e.firebaseapp.com',
    storageBucket: 'fir-crud-a1a2e.appspot.com',
    measurementId: 'G-QJDT4N027T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOCMHLJ5NpHzvVRMXsE21VNkf3Ix7gg7c',
    appId: '1:229653211107:android:6e0e173a13cda1c73be2d6',
    messagingSenderId: '229653211107',
    projectId: 'fir-crud-a1a2e',
    storageBucket: 'fir-crud-a1a2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZZSTW5TOdBs4HiJP8L2TuKJ0qNqwAkd4',
    appId: '1:229653211107:ios:141115cfdf468f403be2d6',
    messagingSenderId: '229653211107',
    projectId: 'fir-crud-a1a2e',
    storageBucket: 'fir-crud-a1a2e.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZZSTW5TOdBs4HiJP8L2TuKJ0qNqwAkd4',
    appId: '1:229653211107:ios:48d3ac7598c93bbb3be2d6',
    messagingSenderId: '229653211107',
    projectId: 'fir-crud-a1a2e',
    storageBucket: 'fir-crud-a1a2e.appspot.com',
    iosBundleId: 'com.example.firebaseCrud.RunnerTests',
  );
}
